[Grand Search]
Name=text-preview-plugin
Version=1.0
Mimetypes=text/*:application/json:application/javascript:application/xml:application/yaml:application/x-yaml:application/x-shellscript:application/x-sh:application/x-php:application/x-ruby:application/x-perl:application/x-python-code:application/sql:application/toml
Valid=true
